// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WifiNetwork = { id: string, ssid: string, security: string, frequency: number, signal: number, };
